//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneCliM.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhoneCliM.Resources.LogMessages", typeof(LogMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By connecting with the phone the your own phonenumber was not a number: {0}.
        /// </summary>
        internal static string CredentialsOwnNumber {
            get {
                return ResourceManager.GetString("CredentialsOwnNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        internal static string CredentialsPassword {
            get {
                return ResourceManager.GetString("CredentialsPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New phone url: {0}.
        /// </summary>
        internal static string CredentialsPhoneUrl {
            get {
                return ResourceManager.GetString("CredentialsPhoneUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New user name: {0}.
        /// </summary>
        internal static string CredentialsUser {
            get {
                return ResourceManager.GetString("CredentialsUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default region could not be set. {0} is not a valid value..
        /// </summary>
        internal static string ErrorImpossibleDefaultRegion {
            get {
                return ResourceManager.GetString("ErrorImpossibleDefaultRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error occured while checking if the string is a valid Phonenumber: {0}.
        /// </summary>
        internal static string ErrorPhoneNumberValid {
            get {
                return ResourceManager.GetString("ErrorPhoneNumberValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After several unsuccessful login attempts, the login process was blocked! It will be available again in about 60 seconds..
        /// </summary>
        internal static string LoginBlocked {
            get {
                return ResourceManager.GetString("LoginBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By connecting with the phone the no connection was possible: {0}.
        /// </summary>
        internal static string NoConnection {
            get {
                return ResourceManager.GetString("NoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By connecting with the phone the ping failed..
        /// </summary>
        internal static string PingImpossible {
            get {
                return ResourceManager.GetString("PingImpossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By connecting with the phone the credentials were wrong: {0}.
        /// </summary>
        internal static string WrongCredentials {
            get {
                return ResourceManager.GetString("WrongCredentials", resourceCulture);
            }
        }
    }
}
