//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneCliM.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageBoxMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageBoxMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhoneCliM.Resources.MessageBoxMessages", typeof(MessageBoxMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wollen Sie die Nummer {0} jetzt anrufen?.
        /// </summary>
        internal static string AskIfCall {
            get {
                return ResourceManager.GetString("AskIfCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nach mehreren erfolglosen Login Versuchen wurde der Login Vorgang blockiert! Er wird in 60 Sekunden wieder verfügbar sein..
        /// </summary>
        internal static string LoginBlocked {
            get {
                return ResourceManager.GetString("LoginBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wenn Sie ein Passwort verwenden müssen Sie auch einen Benutzer dazu angeben.
        ///Bitte stellen Sie bei Ihrem Snom-Telefon einen Benutzer ein und geben Sie diesen an..
        /// </summary>
        internal static string NoName {
            get {
                return ResourceManager.GetString("NoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie eine gültige IP Adresse ein..
        /// </summary>
        internal static string NotAnIpAddress {
            get {
                return ResourceManager.GetString("NotAnIpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es sind keine Einstellungen für die Telefonverbindung vorhanden.
        ///Bitte stellen Sie diese ein..
        /// </summary>
        internal static string NotConfigured {
            get {
                return ResourceManager.GetString("NotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Verbindung zu Ihrem Telefon wurde erfolgreich hergestellt..
        /// </summary>
        internal static string SettingsSaved {
            get {
                return ResourceManager.GetString("SettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Anmeldedaten sind nicht korrekt. Bitte überprüfen Sie Ihre Eingabe..
        /// </summary>
        internal static string WrongCredentials {
            get {
                return ResourceManager.GetString("WrongCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unter der IP Adresse konnte kein Gerät erreicht werden. Bitte überprüfen Sie Ihre Eingabe..
        /// </summary>
        internal static string WrongIpAddress {
            get {
                return ResourceManager.GetString("WrongIpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurde keine oder eine Ungültige Kurzwahl eingegeben.
        /// </summary>
        internal static string WrongOwnNumber {
            get {
                return ResourceManager.GetString("WrongOwnNumber", resourceCulture);
            }
        }
    }
}
